### PR TITLE
Fixed a few typos

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by alberlin232** [comment]
Hello,

I am Abraham Berlin a Computer Science undergrad at Lehigh University. Thank you for your PR and reading over our project. It is exciting to know someone not on our team as looked at it!! I am curious to hear what kind of interest you have in our project if any at? The goal of the project (for some reason not written in the README) is to provide a python package that can score ensemble models for influenza like illnesses. This is done by assessing ensemble models with the same base models and simulating large numbers of time-series to create an equal playing field. The hope is by doing this to create comparable scores.

**Comment by pitmonticone** [comment]
Hi @alberlin232, 

First of all, thank you all for the development and maintenance of this project! 

I'm interested in infectious disease data management and simulation modelling open software (project-specific repositories or packages) in R, Python and Julia tackling typical IDE tasks such as situational awareness, nowcasting projection and evaluation, forecasting projection and evaluation, prospective and retrospective scenario analysis to eventually support the preparedness, surveillance, response, control and prevention of outbreaks, epidemics and pandemics. 

An account I follow starred a repo of the [computationalUncertaintyLab](https://github.com/computationalUncertaintyLab) organisation, I've noticed and explored a bit.

PS: I already knew about the [US COVID-19 Forecast Hub](https://github.com/reichlab/covid19-forecast-hub) and I I'm very interested in ethically-relevant quantitative analyses (e.g. intersection between [EA](https://www.effectivealtruism.org) and [Metaculus](https://www.metaculus.com/) so I became aware of the existence of computationalUncertaintyLab by following @nikosbosse and @tomcm39 on Twitter (e.g. [this](https://twitter.com/tomcm39/status/1545515408131776518?s=20&t=-S_jWah2oK7FDkadGFK2tQ) and [this](https://twitter.com/nikosbosse/status/1549813373365354496?s=20&t=-S_jWah2oK7FDkadGFK2tQ)).

**Comment by nikosbosse** [comment]
Great to meet you @pitmonticone !

**Comment by pitmonticone** [comment]
Pleased to meet you too, @nikosbosse!

**Comment by pitmonticone** [comment]
Glad to meet you too @tomcm39!

Thank you very much for your kind invitation. I'll certainly let you know as soon as I have a little more time. 

Best regards,
Pietro

**Pull request merged**
